export const FARMS_CONFIG = [
  {
    id: "strawberry",
    name: "Strawberry",
    rusName: "Клубничная",
    tokenName: "STR",
    allianceName: "клубники",
    priceInFRU: 100000,
    miningRate: 10,
    rateFru: 1.68,
    enabled: true,
    icon: "🍓",
    txType: "Straberry Farm",
  },
  {
    id: "cherry",
    name: "Cherry",
    rusName: "Вишневая",
    tokenName: "CHE",
    allianceName: "вишни",
    priceInFRU: 50000,
    miningRate: 200,
    rateFru: 86.4,
    enabled: true,
    icon: "🍒",
    txType: "Cherry Farm",
  },
  {
    id: "coconut",
    name: "Coconut",
    rusName: "Кокосовая",
    tokenName: "COC",
    allianceName: "кокосов",
    priceInFRU: 50000,
    miningRate: 2,
    rateFru: 0.7584,
    enabled: false,
    icon: "🥥",
    txType: "Coconut Farm",
  },
];

export type Farm = (typeof FARMS_CONFIG)[number];
