export const FARMS_CONFIG = [
  {
    id: "strawberry",
    name: "Клубничная",
    tokenName: "STR",
    priceInFRU: 100000,
    miningRate: 10,
    rateFru: 1.68,
    enabled: true,
    icon: "🍓",
  },
  {
    id: "cherry",
    name: "Вишневая",
    tokenName: "CHE",
    priceInFRU: 50000,
    miningRate: 200,
    rateFru: 86.4,
    enabled: true,
    icon: "🍒",
  },
  {
    id: "coconut",
    name: "Кокосовая",
    tokenName: "COC",
    priceInFRU: 50000,
    miningRate: 2,
    rateFru: 0.7584,
    enabled: false,
    icon: "🥥",
  },
];
