/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WalletImport } from './routes/wallet'
import { Route as TasksImport } from './routes/tasks'
import { Route as FriendsImport } from './routes/friends'
import { Route as FermImport } from './routes/ferm'
import { Route as CreateAllianceImport } from './routes/create-alliance'
import { Route as ChangeImport } from './routes/change'
import { Route as ChampImport } from './routes/champ'
import { Route as AlliancesImport } from './routes/alliances'
import { Route as IndexImport } from './routes/index'
import { Route as AllianceIdImport } from './routes/alliance.$id'

// Create/Update Routes

const WalletRoute = WalletImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRoute,
} as any)

const TasksRoute = TasksImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRoute,
} as any)

const FriendsRoute = FriendsImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRoute,
} as any)

const FermRoute = FermImport.update({
  id: '/ferm',
  path: '/ferm',
  getParentRoute: () => rootRoute,
} as any)

const CreateAllianceRoute = CreateAllianceImport.update({
  id: '/create-alliance',
  path: '/create-alliance',
  getParentRoute: () => rootRoute,
} as any)

const ChangeRoute = ChangeImport.update({
  id: '/change',
  path: '/change',
  getParentRoute: () => rootRoute,
} as any)

const ChampRoute = ChampImport.update({
  id: '/champ',
  path: '/champ',
  getParentRoute: () => rootRoute,
} as any)

const AlliancesRoute = AlliancesImport.update({
  id: '/alliances',
  path: '/alliances',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AllianceIdRoute = AllianceIdImport.update({
  id: '/alliance/$id',
  path: '/alliance/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/alliances': {
      id: '/alliances'
      path: '/alliances'
      fullPath: '/alliances'
      preLoaderRoute: typeof AlliancesImport
      parentRoute: typeof rootRoute
    }
    '/champ': {
      id: '/champ'
      path: '/champ'
      fullPath: '/champ'
      preLoaderRoute: typeof ChampImport
      parentRoute: typeof rootRoute
    }
    '/change': {
      id: '/change'
      path: '/change'
      fullPath: '/change'
      preLoaderRoute: typeof ChangeImport
      parentRoute: typeof rootRoute
    }
    '/create-alliance': {
      id: '/create-alliance'
      path: '/create-alliance'
      fullPath: '/create-alliance'
      preLoaderRoute: typeof CreateAllianceImport
      parentRoute: typeof rootRoute
    }
    '/ferm': {
      id: '/ferm'
      path: '/ferm'
      fullPath: '/ferm'
      preLoaderRoute: typeof FermImport
      parentRoute: typeof rootRoute
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsImport
      parentRoute: typeof rootRoute
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksImport
      parentRoute: typeof rootRoute
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletImport
      parentRoute: typeof rootRoute
    }
    '/alliance/$id': {
      id: '/alliance/$id'
      path: '/alliance/$id'
      fullPath: '/alliance/$id'
      preLoaderRoute: typeof AllianceIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alliances': typeof AlliancesRoute
  '/champ': typeof ChampRoute
  '/change': typeof ChangeRoute
  '/create-alliance': typeof CreateAllianceRoute
  '/ferm': typeof FermRoute
  '/friends': typeof FriendsRoute
  '/tasks': typeof TasksRoute
  '/wallet': typeof WalletRoute
  '/alliance/$id': typeof AllianceIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alliances': typeof AlliancesRoute
  '/champ': typeof ChampRoute
  '/change': typeof ChangeRoute
  '/create-alliance': typeof CreateAllianceRoute
  '/ferm': typeof FermRoute
  '/friends': typeof FriendsRoute
  '/tasks': typeof TasksRoute
  '/wallet': typeof WalletRoute
  '/alliance/$id': typeof AllianceIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/alliances': typeof AlliancesRoute
  '/champ': typeof ChampRoute
  '/change': typeof ChangeRoute
  '/create-alliance': typeof CreateAllianceRoute
  '/ferm': typeof FermRoute
  '/friends': typeof FriendsRoute
  '/tasks': typeof TasksRoute
  '/wallet': typeof WalletRoute
  '/alliance/$id': typeof AllianceIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alliances'
    | '/champ'
    | '/change'
    | '/create-alliance'
    | '/ferm'
    | '/friends'
    | '/tasks'
    | '/wallet'
    | '/alliance/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alliances'
    | '/champ'
    | '/change'
    | '/create-alliance'
    | '/ferm'
    | '/friends'
    | '/tasks'
    | '/wallet'
    | '/alliance/$id'
  id:
    | '__root__'
    | '/'
    | '/alliances'
    | '/champ'
    | '/change'
    | '/create-alliance'
    | '/ferm'
    | '/friends'
    | '/tasks'
    | '/wallet'
    | '/alliance/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlliancesRoute: typeof AlliancesRoute
  ChampRoute: typeof ChampRoute
  ChangeRoute: typeof ChangeRoute
  CreateAllianceRoute: typeof CreateAllianceRoute
  FermRoute: typeof FermRoute
  FriendsRoute: typeof FriendsRoute
  TasksRoute: typeof TasksRoute
  WalletRoute: typeof WalletRoute
  AllianceIdRoute: typeof AllianceIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlliancesRoute: AlliancesRoute,
  ChampRoute: ChampRoute,
  ChangeRoute: ChangeRoute,
  CreateAllianceRoute: CreateAllianceRoute,
  FermRoute: FermRoute,
  FriendsRoute: FriendsRoute,
  TasksRoute: TasksRoute,
  WalletRoute: WalletRoute,
  AllianceIdRoute: AllianceIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/alliances",
        "/champ",
        "/change",
        "/create-alliance",
        "/ferm",
        "/friends",
        "/tasks",
        "/wallet",
        "/alliance/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/alliances": {
      "filePath": "alliances.tsx"
    },
    "/champ": {
      "filePath": "champ.tsx"
    },
    "/change": {
      "filePath": "change.tsx"
    },
    "/create-alliance": {
      "filePath": "create-alliance.tsx"
    },
    "/ferm": {
      "filePath": "ferm.tsx"
    },
    "/friends": {
      "filePath": "friends.tsx"
    },
    "/tasks": {
      "filePath": "tasks.tsx"
    },
    "/wallet": {
      "filePath": "wallet.tsx"
    },
    "/alliance/$id": {
      "filePath": "alliance.$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
